timeout: 25m

options:
  machineType: E2_HIGHCPU_32
  volumes:
    - name: kubeconfig
      path: /kube
  logging: CLOUD_LOGGING_ONLY
  env: 
    - KUBECONFIG=/kube/config

availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/ci-test-cluster-config/versions/1
    env: CI_KUBE_CONFIG

steps:
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: kube-login
    entrypoint: /bin/bash
    secretEnv:
      - CI_KUBE_CONFIG
    args:
      - -c
      - echo $$CI_KUBE_CONFIG > $$KUBECONFIG

  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: kube-test
    env:
      - TEST_KUBE=true
    entrypoint: /bin/bash
    args:
      - -c
      - make rdpclient integration-kube
    timeout: 20m