issues:
  exclude-rules:
    - linters: gosimple
      text: "S1002: should omit comparison to bool constant"
    # EXC0002 (https://golangci-lint.run/usage/configuration/)
    - linters: golint
      text: "(comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)"
    # EXC0011 (https://golangci-lint.run/usage/configuration/)
    - linters: stylecheck
      text: "(comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)"
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unused
    - unconvert
    - varcheck

output:
  uniq-by-line: false

run:
  skip-dirs:
    - vendor
  skip-dirs-use-default: false
  timeout: 5m
