steps:
  # Run non-root integration tests. The root user is selected by docker image.
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.0.1
    id: root-integration-test
    args: ['make', 'rdpclient', 'integration-root']
    timeout: 10m

  # Reconfigure the workspace for the non-root user
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.0.1
    id: reconfigure-for-nonroot-user
    args: ['chown', '-R', 'ci:ci', '/workspace']
    timeout: 10m

  # Run non-root integration tests. The non-root user is selected by docker image.
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-nonroot:v0.0.1
    id: nonroot-integration-test
    env:
      - TELEPORT_ETCD_TEST="yes"
    args: ['make', 'start-etcd', 'integration']
    timeout: 60m

timeout: 60m
options:
  env: 
    - GOMODCACHE=/workspace/.gomodcacheci
  machineType: E2_HIGHCPU_32
  
